version: '3.0'

networks:
  default:
    driver: bridge

services:
  server:
    container_name: "server_c"
    profiles:
      - server
    command: bash -c "./bin/main"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      CLIENT_OPT: ${CLIENT_OPT_SERVER}
      IP_SERVER: ${IP_SERVER_SERVER}
      IP_CLIENT: ${IP_CLIENT_SERVER}
      MESSAGE: ${MESSAGE_SERVER}
    volumes:
      - "./src/:/src/"
    ports:
      - "8080:8080/tcp"
      - "8888:8888/tcp"
      - "8080:8080/udp"
      - "8888:8888/udp"
    networks:
      - default

  client:
    container_name: "client_c"
    profiles:
      - client
    command: bash -c "./bin/main"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - "./src/:/src/"
    ports:
      - "8080:8080/tcp"
      - "8888:8888/tcp"
      - "8080:8080/udp"
      - "8888:8888/udp"
    environment:
      CLIENT_OPT: ${CLIENT_OPT_CLIENT}
      IP_SERVER: ${IP_SERVER_CLIENT}
      IP_CLIENT: ${IP_CLIENT_CLIENT}
      MESSAGE: ${MESSAGE_CLIENT}
    networks:
      - default
